image: golang:1.18

variables:
  TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_PIPELINE_ID
  BRANCH_NAME: $CI_COMMIT_REF_NAME
  SERVICE: ${SERVICE_NAME_${BRANCH_NAME}}
  SERVER_USER: ${SERVER_USER_${BRANCH_NAME}}
  SERVER_IP: ${SERVER_IP_${BRANCH_NAME}}
  SSH_KEY_SSO: ${SSH_ACCESS_KEY_${BRANCH_NAME}}
.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

stages:
  - test
  - setup
  - publish
  - deploy
test:
  extends: .go-cache
  stage: test
  services:
    - redis:latest
    - name: cockroachdb/cockroach:latest
      alias: db
      command: ["start-single-node", "--insecure"]
    - name: bitnami/zookeeper:3.8
      alias: zookeeper
    - name: bitnami/kafka:3.3
      alias: kafka
  variables:
    FF_NETWORK_PER_BUILD: 1
    KAFKA_BROKER_ID: 1
    KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
    KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
    KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ALLOW_PLAINTEXT_LISTENER: "yes"
    ALLOW_ANONYMOUS_LOGIN: "yes"
    KAFKA_CREATE_TOPICS: "example-topic"
  tags:
    - sso
  before_script:
    - apt update && apt install openssh-client
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_ACCESS_KEY" | tr -d '\r' | ssh-add -
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - go env -w GOPRIVATE="gitlab.com/2ftimeplc/*"
    - printf "machine gitlab.com\nlogin 2ftimesgitlab@gmail.com\npassword $ACCESS_TOKEN" > ~/.netrc
    - printf '[user]\n\temail = 2ftimesgitlab@gmail.com\n\tname = Two F Times Trading PLC\n\n[url "ssh://git@gitlab.com/"]\n\tinsteadOf = https://gitlab.com/' > ~/.gitconfig

  script:
    - CONFIG_NAME=$CONFIG_NAME go test ./... -count=1
  except:
    - staging
    - pre_production
    - production

install_dependencies:
  stage: setup
  image: golang:1.19.3-alpine3.16
  tags:
    - sso
  before_script:
    - mkdir -p .go
    - apk update && apk add openssh-client
    - apk add git
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_ACCESS_KEY" | tr -d '\r' | ssh-add -
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - go env -w GOPRIVATE="gitlab.com/2ftimeplc/*"
    - printf "machine gitlab.com\nlogin 2ftimesgitlab@gmail.com\npassword $ACCESS_TOKEN" > ~/.netrc
    - printf '[user]\n\temail = 2ftimesgitlab@gmail.com\n\tname = Two F Times Trading PLC\n\n[url "ssh://git@gitlab.com/"]\n\tinsteadOf = https://gitlab.com/' > ~/.gitconfig
  script:
    - go mod vendor
  cache:
    key: $CI_PROJECT_DIR
    paths:
      - vendor/
    policy: push
  only:
    changes:
      - go.mod
      - go.sum
    refs:
      - staging
      - pre_production
      - production

publish:
  image: docker:latest
  stage: publish
  cache:
    key: $CI_PROJECT_DIR
    paths:
      - vendor/
    policy: pull
  tags:
    - sso
  services:
    - docker:dind
  script:
    - docker build -t $TAG .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG
  only:
    refs:
      - staging
      - pre_production
      - production

deployment:
  image: alpine:latest
  stage: deploy
  tags:
    - sso
  before_script:
    - apk update && apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY_SSO" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    - ssh $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh $SERVER_USER@$SERVER_IP "docker pull $TAG"
    - ssh $SERVER_USER@$SERVER_IP "docker service update --image $TAG --force --with-registry-auth $SERVICE"

  only:
    refs:
      - staging
      - pre_production
      - production
