image: golang:1.18

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

stages:
  - test
test:
  extends: .go-cache
  stage: test
  services:
    - redis:latest
    - name: cockroachdb/cockroach:latest
      alias: db
      command: ["start-single-node", "--insecure"]
  tags:
    - sso
  before_script:
    - go env -w GOPRIVATE="gitlab.com/2ftimeplc/*"
    - printf 'machine gitlab.com\nlogin 2ftimesgitlab@gmail.com\npassword $ACCESS_TOKEN' > ~/.netrc
    - printf '[user]\n\temail = 2ftimesgitlab@gmail.com\n\tname = Two F Times Trading PLC\n\n[url "ssh://git@gitlab.com/"]\n\tinsteadOf = https://gitlab.com/' > ~/.gitconfig

  script:
    - go test -v ./... -p=1 -count=1