// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: client.sql

package db

import (
	"context"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (
    name,
    client_type,
    redirect_uris,
    scopes,
    secret,
    logo_url
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, client_type, redirect_uris, scopes, secret, logo_url, status, created_at
`

type CreateClientParams struct {
	Name         string `json:"name"`
	ClientType   string `json:"client_type"`
	RedirectUris string `json:"redirect_uris"`
	Scopes       string `json:"scopes"`
	Secret       string `json:"secret"`
	LogoUrl      string `json:"logo_url"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.Name,
		arg.ClientType,
		arg.RedirectUris,
		arg.Scopes,
		arg.Secret,
		arg.LogoUrl,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClientType,
		&i.RedirectUris,
		&i.Scopes,
		&i.Secret,
		&i.LogoUrl,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
