// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: kafka.sql

package db

import (
	"context"
)

const getKafkaOffset = `-- name: GetKafkaOffset :one
SELECT offset_val
from kafka_offsets
where true
LIMIT 1
`

func (q *Queries) GetKafkaOffset(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getKafkaOffset)
	var offset_val int32
	err := row.Scan(&offset_val)
	return offset_val, err
}

const setKafkaOffset = `-- name: SetKafkaOffset :exec
UPDATE kafka_offsets
SET offset_val = $1
WHERE true
`

func (q *Queries) SetKafkaOffset(ctx context.Context, offsetVal int32) error {
	_, err := q.db.Exec(ctx, setKafkaOffset, offsetVal)
	return err
}
