// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Authcode struct {
	ID          uuid.UUID `json:"id"`
	Code        string    `json:"code"`
	UserID      uuid.UUID `json:"user_id"`
	Status      string    `json:"status"`
	Scope       string    `json:"scope"`
	RedirectUri string    `json:"redirect_uri"`
	ClientID    uuid.UUID `json:"client_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type User struct {
	ID             uuid.UUID      `json:"id"`
	FirstName      string         `json:"first_name"`
	MiddleName     string         `json:"middle_name"`
	LastName       string         `json:"last_name"`
	Email          sql.NullString `json:"email"`
	Phone          string         `json:"phone"`
	Password       string         `json:"password"`
	UserName       string         `json:"user_name"`
	Gender         string         `json:"gender"`
	ProfilePicture sql.NullString `json:"profile_picture"`
	Status         sql.NullString `json:"status"`
	CreatedAt      time.Time      `json:"created_at"`
}
