// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"
)

type User struct {
	ID             int64
	FirstName      string
	MiddleName     string
	LastName       string
	Email          sql.NullString
	Phone          string
	Password       string
	UserName       string
	Gender         string
	ProfilePicture sql.NullString
	Status         sql.NullString
	CreatedAt      time.Time
}
