// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: refreshtoken.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const removeRefreshToken = `-- name: RemoveRefreshToken :exec
DELETE FROM refreshtokens WHERE code = $1
`

func (q *Queries) RemoveRefreshToken(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, removeRefreshToken, code)
	return err
}

const saveRefreshToken = `-- name: SaveRefreshToken :one
INSERT INTO refreshtokens (
    expires_at,
    user_id,
    scope,
    redirect_uri,
    client_id,
    refreshtoken,
    code
) VALUES (
    $1, $2, $3, $4, $5,$6,$7
)
RETURNING id, refreshtoken, code, user_id, scope, redirect_uri, expires_at, client_id, created_at, updated_at
`

type SaveRefreshTokenParams struct {
	ExpiresAt    time.Time      `json:"expires_at"`
	UserID       uuid.UUID      `json:"user_id"`
	Scope        sql.NullString `json:"scope"`
	RedirectUri  sql.NullString `json:"redirect_uri"`
	ClientID     uuid.UUID      `json:"client_id"`
	Refreshtoken string         `json:"refreshtoken"`
	Code         string         `json:"code"`
}

func (q *Queries) SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) (Refreshtoken, error) {
	row := q.db.QueryRow(ctx, saveRefreshToken,
		arg.ExpiresAt,
		arg.UserID,
		arg.Scope,
		arg.RedirectUri,
		arg.ClientID,
		arg.Refreshtoken,
		arg.Code,
	)
	var i Refreshtoken
	err := row.Scan(
		&i.ID,
		&i.Refreshtoken,
		&i.Code,
		&i.UserID,
		&i.Scope,
		&i.RedirectUri,
		&i.ExpiresAt,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
