// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: resource_server.sql

package db

import (
	"context"
)

const createResourceServer = `-- name: CreateResourceServer :one
INSERT INTO resource_servers (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateResourceServer(ctx context.Context, name string) (ResourceServer, error) {
	row := q.db.QueryRow(ctx, createResourceServer, name)
	var i ResourceServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
