// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: scope.sql

package db

import (
	"context"
	"database/sql"
)

const createScope = `-- name: CreateScope :one
INSERT INTO scopes (
    name,
    description,
    resource_server_name
) VALUES (
    $1, $2, $3
) RETURNING id, name, description, resource_server_id, resource_server_name, status, created_at
`

type CreateScopeParams struct {
	Name               string         `json:"name"`
	Description        string         `json:"description"`
	ResourceServerName sql.NullString `json:"resource_server_name"`
}

func (q *Queries) CreateScope(ctx context.Context, arg CreateScopeParams) (Scope, error) {
	row := q.db.QueryRow(ctx, createScope, arg.Name, arg.Description, arg.ResourceServerName)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ResourceServerID,
		&i.ResourceServerName,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteScope = `-- name: DeleteScope :one
DELETE FROM scopes WHERE name = $1 RETURNING id, name, description, resource_server_id, resource_server_name, status, created_at
`

func (q *Queries) DeleteScope(ctx context.Context, name string) (Scope, error) {
	row := q.db.QueryRow(ctx, deleteScope, name)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ResourceServerID,
		&i.ResourceServerName,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getScope = `-- name: GetScope :one
SELECT id, name, description, resource_server_id, resource_server_name, status, created_at FROM scopes WHERE name = $1
`

func (q *Queries) GetScope(ctx context.Context, name string) (Scope, error) {
	row := q.db.QueryRow(ctx, getScope, name)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ResourceServerID,
		&i.ResourceServerName,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getScopesByResourceServerName = `-- name: GetScopesByResourceServerName :many
SELECT id, name, description, resource_server_id, resource_server_name, status, created_at
FROM scopes
WHERE resource_server_name = $1
`

func (q *Queries) GetScopesByResourceServerName(ctx context.Context, resourceServerName sql.NullString) ([]Scope, error) {
	rows, err := q.db.Query(ctx, getScopesByResourceServerName, resourceServerName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scope
	for rows.Next() {
		var i Scope
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ResourceServerID,
			&i.ResourceServerName,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScope = `-- name: UpdateScope :one
UPDATE scopes
SET 
 description = $2
WHERE name = $1
RETURNING id, name, description, resource_server_id, resource_server_name, status, created_at
`

type UpdateScopeParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) UpdateScope(ctx context.Context, arg UpdateScopeParams) (Scope, error) {
	row := q.db.QueryRow(ctx, updateScope, arg.Name, arg.Description)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ResourceServerID,
		&i.ResourceServerName,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
