debug: false
dev: true
database:
  url: postgresql://root@db:26257/defaultdb?sslmode=disable
migration:
  path: internal/constant/query/schemas
casbin:
  path: config/casbin.conf
redis:
  url: redis://redis:6379/0
  otp_expire_time: 300s
  session_expire_time: 3600s
  consent_expire_time: 3600s
  authcode_expire_time: 3600s

server:
  port: 8000
  timeout: 30s
  login:
    access_token:
      expire_time: 1h
    refresh_token:
      expire_time: 265d
    id_token:
      expire_time: 24h
  oauth2:
    error_uri: http://front-end/oauth2/error
    consent_uri: http://front-end/oauth2/consent
frontend:
  error_url: https://www.google.com/
  consent_url: https://www.google.com/
  logout_url: https://www.google.com/
private_key: privatekey.example.pem
public_key: publickey.example.pem
sms:
  username: user1
  password: test@pass
  server: "https://sms.rideplus.co"
  templates:
    otp: "%v is your Ride Auth authentication code."
    password: "%v is your Ride password. Please login and reset it."
cors:
  origin:
    - "*"
  allow_credentials: true
  headers:
    - "*"
  methods:
    - GET
    - POST
    - PUT
    - OPTIONS
    - DELETE
    - PATCH
kafka:
  topic: example-topic
  url: kafka:9092
  group_id: test
  
mini_ride:
  username: mini-ride
  password: fbL50Wgr1E7o3vvmR

assets:
  profile_picture_dist: ../../../../static/profile_picture/
  profile_picture_max_size: 2000001