version: 1
packages:
  - name: "db"
    path: "../internal/constant/model/db"
    engine: "postgresql"
    sql_package: "pgx/v4"
    schema: "../internal/constant/query/schemas"
    queries: "../internal/constant/query/queries"