// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "2F Capital Support Email",
            "url": "http://www.2fcapital.com",
            "email": "info@1f-capital.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/clients": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "returns all clients based on the filters and pagination given",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "returns all clients that satisfy the given filters",
                "parameters": [
                    {
                        "type": "string",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "link_operator",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.Client"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "Create a client",
                "parameters": [
                    {
                        "description": "client",
                        "name": "client",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Client"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Client"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clients/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "returns client that holds given id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "returns client",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Client"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "changes client information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "changes client information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete  client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "Delete  client",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clients/{id}/status": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "changes client status so that they can revoke client's",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "changes client status",
                "parameters": [
                    {
                        "description": "status",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateClientStatus"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Login a user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login a user.",
                "parameters": [
                    {
                        "description": "login_credential",
                        "name": "login_credential",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginCredential"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "invalid input",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "logout user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "logout  user.",
                "parameters": [
                    {
                        "description": "logoutParam",
                        "name": "tokenParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.InternalRefreshTokenRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "invalid input",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/oauth/approveConsent": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "is used to approve consent.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2"
                ],
                "summary": "Consent Approval..",
                "parameters": [
                    {
                        "description": "consent_id",
                        "name": "consent_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "redirect response",
                        "schema": {
                            "$ref": "#/definitions/dto.RedirectResponse"
                        },
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "redirect_uri"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid input",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        },
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "redirect_uri"
                            }
                        }
                    }
                }
            }
        },
        "/oauth/authorize": {
            "get": {
                "description": "is used to obtain authorization code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2"
                ],
                "summary": "Authorize.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "response_type",
                        "name": "response_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "client_id",
                        "name": "client_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "state",
                        "name": "state",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "scope",
                        "name": "scope",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "redirect_uri",
                        "name": "redirect_uri",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "redirect_uri"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        },
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "redirect_uri"
                            }
                        }
                    }
                }
            }
        },
        "/oauth/authorizedClients": {
            "get": {
                "description": "It returns all clients that have resource access other than openid for the logged in user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2"
                ],
                "summary": "returns all authorized clients",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.AuthorizedClientsResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/oauth/consent/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "is used to get consent by id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2"
                ],
                "summary": "GetConsentByID.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "user_id",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ConsentResponse"
                        }
                    },
                    "400": {
                        "description": "invalid input",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/oauth/logout": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "this is requested from truest client only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2"
                ],
                "summary": "rp-logout.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id_token_hint",
                        "name": "id_token_hint",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "post_logout_redirect_uri",
                        "name": "post_logout_redirect_uri",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "state",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "redirect_uri"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        },
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "redirect_uri"
                            }
                        }
                    }
                }
            }
        },
        "/oauth/openIDAuthorizedClients": {
            "get": {
                "description": "It returns all clients that have only openid access for the logged-in user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2"
                ],
                "summary": "returns all only-openid authorized clients",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.AuthorizedClientsResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/oauth/rejectConsent": {
            "post": {
                "description": "is used to reject consent.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2"
                ],
                "summary": "Consent Rejection.",
                "parameters": [
                    {
                        "description": "consent_id",
                        "name": "consent_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "failure_reason",
                        "name": "failure_reason",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "redirect response",
                        "schema": {
                            "$ref": "#/definitions/dto.RedirectResponse"
                        },
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "redirect_uri"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid input",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        },
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "redirect_uri"
                            }
                        }
                    }
                }
            }
        },
        "/oauth/revokeClient": {
            "post": {
                "description": "It is used by the user in case he/she wants to revoke access for a certain client.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2"
                ],
                "summary": "revokes client access",
                "parameters": [
                    {
                        "description": "revokeBody",
                        "name": "revokeBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request_models.RevokeClientBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/oauth/scopes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "returns all scopes that satisfy given filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scope"
                ],
                "summary": "returns all scopes that satisfy given filters",
                "parameters": [
                    {
                        "type": "string",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "link_operator",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.Scope"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new scope",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scope"
                ],
                "summary": "Create a new scope",
                "operationId": "create-scope",
                "parameters": [
                    {
                        "description": "Create a new scope",
                        "name": "scope",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Scope"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.Scope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/oauth/scopes/{name}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a scope",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scope"
                ],
                "summary": "Get a scope",
                "operationId": "get-scope",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Scope name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Scope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "update  scope",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scope"
                ],
                "summary": "update  scope",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "scope",
                        "name": "scope",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateScopeParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete  scope",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scope"
                ],
                "summary": "Delete  scope",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/oauth/token": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "is used to exchange token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2"
                ],
                "summary": "exchange token.",
                "parameters": [
                    {
                        "description": "tokenParam",
                        "name": "tokenParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AccessTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "invalid input",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "no record of code found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/otp": {
            "get": {
                "description": "is used to request otp for login and signup",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Request otp.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "phone",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "login",
                            "signup"
                        ],
                        "type": "string",
                        "description": "type can be login or signup",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "invalid input",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "get's user profile.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "get's user profile.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "update user profile.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "update user profile.",
                "parameters": [
                    {
                        "description": "user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profile/password": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "change's user password..",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "change's user password..",
                "parameters": [
                    {
                        "description": "ChangePasswordParam",
                        "name": "ChangePasswordParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ChangePasswordParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profile/phone": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "change user phone number.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "change user phone number.",
                "parameters": [
                    {
                        "description": "ChangePhoneParam",
                        "name": "ChangePhoneParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ChangePhoneParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profile/picture": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "update user profile picture.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "update user profile picture.",
                "parameters": [
                    {
                        "type": "file",
                        "description": "image",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/refreshToken": {
            "get": {
                "description": "refresh access token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "refresh access token.",
                "parameters": [
                    {
                        "description": "refreshTokenParam",
                        "name": "tokenParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.InternalRefreshTokenRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "invalid input",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Register a new user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user.",
                "parameters": [
                    {
                        "description": "user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/resourceServers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "returns all resource servers based on the filters and pagination given",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resourceServer"
                ],
                "summary": "returns all resource servers that satisfy the given filters",
                "parameters": [
                    {
                        "type": "string",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "link_operator",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ResourceServer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new resource server",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resourceServer"
                ],
                "summary": "Create a resource server",
                "parameters": [
                    {
                        "description": "resource_server",
                        "name": "client",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ResourceServer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResourceServer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/roles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "returns all roles based on the filters and pagination given",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "returns all roles that satisfy the given filters",
                "parameters": [
                    {
                        "type": "string",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "link_operator",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.Role"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "create a role with specified name and permission list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "create role",
                "operationId": "create-role",
                "parameters": [
                    {
                        "description": "role",
                        "name": "role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Role"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Role"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/roles/permissions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all permissions that are predefined and fixed for this server",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "Get all permissions",
                "operationId": "get-all-permissions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "category of permissions",
                        "name": "category",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/permissions.Permission"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/roles/{name}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "deletes a role and all user associations with the role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "deletes a role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/roles/{name}/status": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "changes role status so that they can revoke a role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "changes role status",
                "parameters": [
                    {
                        "description": "status",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateRoleStatus"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "returns all users based on the filters and pagination given",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "returns all users that satisfy the given filters",
                "parameters": [
                    {
                        "type": "string",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "link_operator",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.User"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "create a new user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "create a new user.",
                "parameters": [
                    {
                        "description": "user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "get user details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "get user details.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}/role": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "updates the role for the user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "updates the role for the user",
                "parameters": [
                    {
                        "description": "role",
                        "name": "role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AssignRole"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}/status": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "changes user status to ACTIVE or INACTIVE",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "changes user status",
                "parameters": [
                    {
                        "description": "user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{phone}/exists": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "check's if phone exists.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "miniRide"
                ],
                "summary": "check's if phone exists.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "phone",
                        "name": "phone",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MiniRideResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AccessTokenRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Authorization code generated by the authorization server.",
                    "type": "string"
                },
                "grant_type": {
                    "description": "GrantType is the type of flow the client is following to get access token.\nIt can be either authorization_code or refresh_token.",
                    "type": "string"
                },
                "redirect_uri": {
                    "description": "Redirection URI used in the initial authorization request.",
                    "type": "string"
                },
                "refresh_token": {
                    "description": "RefreshToken is the opaque string that was given by the auth server when issuing the access token.\nit's used to refresh the access token.",
                    "type": "string"
                }
            }
        },
        "dto.AssignRole": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string"
                }
            }
        },
        "dto.AuthorizedClientsResponse": {
            "type": "object",
            "properties": {
                "auth_scopes": {
                    "description": "AuthScopes is the scopes this authorization is given access to",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Scope"
                    }
                },
                "client_type": {
                    "description": "ClientType is the type of the client.\nIt can be either confidential or public.",
                    "type": "string"
                },
                "created_at": {
                    "description": "AuthGivenAt is the time this client is given authorization at",
                    "type": "string"
                },
                "expires_at": {
                    "description": "AuthExpiresAt is the time this authorization expires at",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier for the client.\nIt is automatically generated when the client is registered.",
                    "type": "string"
                },
                "logo_url": {
                    "description": "LogoURL is the URL of the client's logo.\nIt must be a valid URL.",
                    "type": "string"
                },
                "name": {
                    "description": "Name is the name of the client that will be displayed to the user.",
                    "type": "string"
                },
                "redirect_uris": {
                    "description": "RedirectURIs is the list of redirect URIs of the client.\nEach redirect URI must be a valid URL and must use HTTPS.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scopes": {
                    "description": "Scopes is the list of default scopes of the client if one is not provided.",
                    "type": "string"
                },
                "secret": {
                    "description": "Secret is the secret the client uses to authenticate itself.\nIt is automatically generated when the client is registered.",
                    "type": "string"
                },
                "status": {
                    "description": "Status is the current status of the client.\nIt is set to active by default.",
                    "type": "string"
                },
                "updated_at": {
                    "description": "AuthUpdatedAt is the time this authorization is last updated at",
                    "type": "string"
                }
            }
        },
        "dto.ChangePasswordParam": {
            "type": "object",
            "properties": {
                "new_password": {
                    "description": "NewPassword is the new password of the user.",
                    "type": "string"
                },
                "old_password": {
                    "description": "OldPassword is the previous password of the user.",
                    "type": "string"
                }
            }
        },
        "dto.ChangePhoneParam": {
            "type": "object",
            "properties": {
                "otp": {
                    "description": "OTP is the one time password of the user.",
                    "type": "string"
                },
                "phone": {
                    "description": "Phone is the phone of the user.",
                    "type": "string"
                }
            }
        },
        "dto.Client": {
            "type": "object",
            "properties": {
                "client_type": {
                    "description": "ClientType is the type of the client.\nIt can be either confidential or public.",
                    "type": "string"
                },
                "created_at": {
                    "description": "CreatedAt is the time this client was created at",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier for the client.\nIt is automatically generated when the client is registered.",
                    "type": "string"
                },
                "logo_url": {
                    "description": "LogoURL is the URL of the client's logo.\nIt must be a valid URL.",
                    "type": "string"
                },
                "name": {
                    "description": "Name is the name of the client that will be displayed to the user.",
                    "type": "string"
                },
                "redirect_uris": {
                    "description": "RedirectURIs is the list of redirect URIs of the client.\nEach redirect URI must be a valid URL and must use HTTPS.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scopes": {
                    "description": "Scopes is the list of default scopes of the client if one is not provided.",
                    "type": "string"
                },
                "secret": {
                    "description": "Secret is the secret the client uses to authenticate itself.\nIt is automatically generated when the client is registered.",
                    "type": "string"
                },
                "status": {
                    "description": "Status is the current status of the client.\nIt is set to active by default.",
                    "type": "string"
                }
            }
        },
        "dto.ConsentResponse": {
            "type": "object",
            "properties": {
                "approved": {
                    "description": "Approved tells if this exact scope is previously approved by this user",
                    "type": "boolean"
                },
                "client_id": {
                    "description": "ClientID is the id of the client given at the time of registration",
                    "type": "string"
                },
                "client_logo": {
                    "description": "ClientLogo is the logo url of the client",
                    "type": "string"
                },
                "client_name": {
                    "description": "ClientName is the name of the client",
                    "type": "string"
                },
                "client_trusted": {
                    "description": "ClientTrusted tells if this client is a trusted first party client",
                    "type": "boolean"
                },
                "client_type": {
                    "description": "ClientType is the type of the client\nIt might be confidential or public",
                    "type": "string"
                },
                "scopes": {
                    "description": "Scopes is the list of scopes this consent holds",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Scope"
                    }
                },
                "user_id": {
                    "description": "UserID is the id of the user this consent is being given to",
                    "type": "string"
                }
            }
        },
        "dto.CreateUser": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "CreatedAt is the time when the user is created.\nIt is automatically set when the user is created.",
                    "type": "string"
                },
                "email": {
                    "description": "Email is the email of the user.",
                    "type": "string"
                },
                "first_name": {
                    "description": "FirstName is the first name of the user.",
                    "type": "string"
                },
                "gender": {
                    "description": "Gender is the gender of the user.",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier of the user.\nIt is automatically generated when the user is created.",
                    "type": "string"
                },
                "last_name": {
                    "description": "LastName is the last name of the user.",
                    "type": "string"
                },
                "middle_name": {
                    "description": "MiddleName is the middle name of the user.",
                    "type": "string"
                },
                "password": {
                    "description": "Password is the password of the user.\nIt is only used for logging in with email",
                    "type": "string"
                },
                "phone": {
                    "description": "Phone is the phone of the user.",
                    "type": "string"
                },
                "profile_picture": {
                    "description": "ProfilePicture is the profile picture of the user.\nIt is set on a separate setProfilePicture endpoint.",
                    "type": "string"
                },
                "role": {
                    "description": "Role is the role given to the user being created.",
                    "type": "string"
                },
                "status": {
                    "description": "Status is the status of the user.\nIt is set to active by default after successful registration.",
                    "type": "string"
                },
                "user_name": {
                    "description": "UserName is the username of the user.\nIt is currently of no use",
                    "type": "string"
                }
            }
        },
        "dto.InternalRefreshTokenRequestBody": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "description": "RefreshToken is the opaque string users uses to refresh access token.",
                    "type": "string"
                }
            }
        },
        "dto.LoginCredential": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "Email of the user if for login with password",
                    "type": "string"
                },
                "otp": {
                    "description": "OTP generated from phone number",
                    "type": "string"
                },
                "password": {
                    "description": "Password of the user if for login with password",
                    "type": "string"
                },
                "phone": {
                    "description": "Phone number of the user if for login with otp",
                    "type": "string"
                }
            }
        },
        "dto.MiniRideResponse": {
            "type": "object",
            "properties": {
                "exists": {
                    "type": "boolean"
                },
                "user": {
                    "$ref": "#/definitions/dto.User"
                }
            }
        },
        "dto.RedirectResponse": {
            "type": "object",
            "properties": {
                "location": {
                    "description": "Location is the url of the client or an error page of the front-end that must be navigated to",
                    "type": "string"
                }
            }
        },
        "dto.RegisterUser": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "CreatedAt is the time when the user is created.\nIt is automatically set when the user is created.",
                    "type": "string"
                },
                "email": {
                    "description": "Email is the email of the user.",
                    "type": "string"
                },
                "first_name": {
                    "description": "FirstName is the first name of the user.",
                    "type": "string"
                },
                "gender": {
                    "description": "Gender is the gender of the user.",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier of the user.\nIt is automatically generated when the user is created.",
                    "type": "string"
                },
                "last_name": {
                    "description": "LastName is the last name of the user.",
                    "type": "string"
                },
                "middle_name": {
                    "description": "MiddleName is the middle name of the user.",
                    "type": "string"
                },
                "otp": {
                    "description": "OTP is the one time password of the user.",
                    "type": "string"
                },
                "password": {
                    "description": "Password is the password of the user.\nIt is only used for logging in with email",
                    "type": "string"
                },
                "phone": {
                    "description": "Phone is the phone of the user.",
                    "type": "string"
                },
                "profile_picture": {
                    "description": "ProfilePicture is the profile picture of the user.\nIt is set on a separate setProfilePicture endpoint.",
                    "type": "string"
                },
                "status": {
                    "description": "Status is the status of the user.\nIt is set to active by default after successful registration.",
                    "type": "string"
                },
                "user_name": {
                    "description": "UserName is the username of the user.\nIt is currently of no use",
                    "type": "string"
                }
            }
        },
        "dto.ResourceServer": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "CreatedAt is the time this resource server is created at",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique id for this resource server",
                    "type": "string"
                },
                "name": {
                    "description": "Name is the resource server name.\nIt must be unique across the sso",
                    "type": "string"
                },
                "scopes": {
                    "description": "Scopes is the scopes of this resource server",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Scope"
                    }
                },
                "updated_at": {
                    "description": "UpdatedAt is the time this resource server is updated at",
                    "type": "string"
                }
            }
        },
        "dto.Role": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "CreatedAt is the time this role is created on",
                    "type": "string"
                },
                "name": {
                    "description": "Name is a unique name for the role",
                    "type": "string"
                },
                "permissions": {
                    "description": "Permissions are the list of permissions names this role contains",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "description": "Status is the current status of this role",
                    "type": "string"
                },
                "updated_at": {
                    "description": "UpdatedAt is the time this role is last updated at",
                    "type": "string"
                }
            }
        },
        "dto.Scope": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "date the scope created",
                    "type": "string"
                },
                "description": {
                    "description": "The scope description.",
                    "type": "string"
                },
                "name": {
                    "description": "The scope name.",
                    "type": "string"
                },
                "resource_server_name": {
                    "description": "resource server name",
                    "type": "string"
                }
            }
        },
        "dto.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "AccessToken is the access token for the current login",
                    "type": "string"
                },
                "expires_in": {
                    "description": "ExpiresAt is time the access token is going to be expired.",
                    "type": "string"
                },
                "id_token": {
                    "description": "IDToken is the OpenID specific JWT token",
                    "type": "string"
                },
                "refresh_token": {
                    "description": "RefreshToken is the refresh token for the access token",
                    "type": "string"
                },
                "token_type": {
                    "description": "TokenType is the type of token",
                    "type": "string"
                }
            }
        },
        "dto.UpdateClientStatus": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Status is new status that will replace old status of the user",
                    "type": "string"
                }
            }
        },
        "dto.UpdateRoleStatus": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Status is new status that will replace old status of the role",
                    "type": "string"
                }
            }
        },
        "dto.UpdateScopeParam": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "The scope description.",
                    "type": "string"
                }
            }
        },
        "dto.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "CreatedAt is the time when the user is created.\nIt is automatically set when the user is created.",
                    "type": "string"
                },
                "email": {
                    "description": "Email is the email of the user.",
                    "type": "string"
                },
                "first_name": {
                    "description": "FirstName is the first name of the user.",
                    "type": "string"
                },
                "gender": {
                    "description": "Gender is the gender of the user.",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier of the user.\nIt is automatically generated when the user is created.",
                    "type": "string"
                },
                "last_name": {
                    "description": "LastName is the last name of the user.",
                    "type": "string"
                },
                "middle_name": {
                    "description": "MiddleName is the middle name of the user.",
                    "type": "string"
                },
                "password": {
                    "description": "Password is the password of the user.\nIt is only used for logging in with email",
                    "type": "string"
                },
                "phone": {
                    "description": "Phone is the phone of the user.",
                    "type": "string"
                },
                "profile_picture": {
                    "description": "ProfilePicture is the profile picture of the user.\nIt is set on a separate setProfilePicture endpoint.",
                    "type": "string"
                },
                "status": {
                    "description": "Status is the status of the user.\nIt is set to active by default after successful registration.",
                    "type": "string"
                },
                "user_name": {
                    "description": "UserName is the username of the user.\nIt is currently of no use",
                    "type": "string"
                }
            }
        },
        "model.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code is the error code. It is not status code",
                    "type": "integer"
                },
                "description": {
                    "description": "Description is the error description.",
                    "type": "string"
                },
                "field_error": {
                    "description": "FieldError is the error detail for each field, if available that is.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.FieldError"
                    }
                },
                "message": {
                    "description": "Message is the error message.",
                    "type": "string"
                },
                "stack_trace": {
                    "description": "StackTrace is the stack trace of the error.\nIt is only returned for debugging",
                    "type": "string"
                }
            }
        },
        "model.FieldError": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "Description is the error description for this field.",
                    "type": "string"
                },
                "name": {
                    "description": "Name is the name of the field that caused the error.",
                    "type": "string"
                }
            }
        },
        "model.MetaData": {
            "type": "object",
            "properties": {
                "extra": {
                    "description": "Extra contains other response specific data"
                },
                "filter": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request_models.Filter"
                    }
                },
                "link_operator": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "sort": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request_models.Sort"
                    }
                },
                "total": {
                    "description": "Total is the total number of data without pagination",
                    "type": "integer"
                }
            }
        },
        "model.Response": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Data contains the actual data of the response."
                },
                "error": {
                    "description": "Error contains the error detail if the request was not successful.",
                    "$ref": "#/definitions/model.ErrorResponse"
                },
                "meta_data": {
                    "description": "MetaData contains additional data like filtering, pagination, etc.",
                    "$ref": "#/definitions/model.MetaData"
                },
                "ok": {
                    "description": "OK is only true if the request was successful.",
                    "type": "boolean"
                }
            }
        },
        "permissions.Permission": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "request_models.Filter": {
            "type": "object",
            "properties": {
                "column_field": {
                    "type": "string"
                },
                "operator_value": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "request_models.RevokeClientBody": {
            "type": "object",
            "properties": {
                "client_id": {
                    "description": "ClientID is the id of the client to be revoked access of.\nIt is a required field",
                    "type": "string"
                }
            }
        },
        "request_models.Sort": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "sort": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        },
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "206.189.54.235:8000",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "RidePLUS SSO API",
	Description:      "This is the RidePLUS sso api.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
